[package]
name = "fortanix-vme-eif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpio = "0.2"
flate2 = "1.0"
thiserror = "1.0"
