branches:
  only:
    # Branch for continued development of em-app v0.2.x
    - em-app_v0.2.x
language: rust

matrix:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: 'deb https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main'
              key_url: 'https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key'
            - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-11
            - libclang-common-11-dev
      rust:
        - nightly # need nightly because em-app depends on sgx-isa 0.3 with the sgxstd feature enabled, which requires nightly
      env:
        - RUST_BACKTRACE=1
        - CFLAGS_x86_64_fortanix_unknown_sgx="-isystem/usr/include/x86_64-linux-gnu -mlvi-hardening -mllvm -x86-experimental-lvi-inline-asm-hardening"
        - CC_x86_64_fortanix_unknown_sgx=clang-11
      before_script:
        - rustup target add x86_64-fortanix-unknown-sgx
      script:
        - cargo build --verbose --locked --manifest-path em-app/Cargo.toml --target=x86_64-fortanix-unknown-sgx
