[workspace]
members = [
    "fortanix-vme/aws-nitro-enclaves/eif-tools",
    "fortanix-vme/aws-nitro-enclaves/nsm",
    "fortanix-vme/aws-nitro-enclaves/nitro-attestation-verify",
    "fortanix-vme/aws-nitro-enclaves/tests/nsm-test",
    "fortanix-vme/fortanix-vme-abi",
    "fortanix-vme/fortanix-vme-eif",
    "fortanix-vme/fortanix-vme-runner",
    "fortanix-vme/fortanix-vme-tools",
    "fortanix-vme/tests/hello_world",
    "fortanix-vme/tests/outgoing_connection",
    "fortanix-vme/tests/incoming_connection",
    "fortanix-vme/tests/iron",
    "fortanix-vme/vme-pkix",
    "intel-sgx/aesm-client",
    "intel-sgx/dcap-provider",
    "intel-sgx/dcap-ql-sys",
    "intel-sgx/dcap-ql",
    "intel-sgx/dcap-retrieve-pckid",
    "intel-sgx/enclave-runner",
    "intel-sgx/fortanix-sgx-abi",
    "intel-sgx/fortanix-sgx-tools",
    "intel-sgx/ias",
    "intel-sgx/report-test",
    "intel-sgx/sgxs",
    "intel-sgx/sgx-isa",
    "intel-sgx/sgx_pkix",
    "intel-sgx/sgxs-loaders",
    "intel-sgx/sgxs-tools",
    "ipc-queue",
    "rs-libc",
    "em-app",
    "em-app/examples/get-certificate/",
    "em-app/examples/harmonize/",
]
exclude = ["examples"]

[patch.crates-io]
getrandom = { git = "https://github.com/fortanix/getrandom", branch = "fortanixvme-2023-05-07-alpha" }
libc   = { git = "https://github.com/fortanix/libc", branch = "fortanixvme-2023-05-07-alpha" }
mbedtls = { git = "https://github.com/fortanix/rust-mbedtls", branch = "master" }
nix   = { git = "https://github.com/fortanix/nix.git", branch = "raoul/fortanixvme_r0.20.2" }
serde = { git = "https://github.com/fortanix/serde.git", branch = "master" }
vsock = { git = "https://github.com/fortanix/vsock-rs", branch = "fortanixvme-2023-05-07-alpha" }
rustc-serialize = { git = "https://github.com/jethrogb/rustc-serialize.git", branch = "portability" }
nitro-cli = { git = "https://github.com/aws/aws-nitro-enclaves-cli.git" }
