[workspace]
members = [
    "fortanix-vme/vme-pkix",
    "fortanix-vme/eif-tools",
    "fortanix-vme/fortanix-vme-abi",
    "fortanix-vme/fortanix-vme-runner",
    "fortanix-vme/nsm",
    "fortanix-vme/nitro-attestation-verify",
    "fortanix-vme/tests/hello_world",
    "fortanix-vme/tests/outgoing_connection",
    "fortanix-vme/tests/incoming_connection",
    "fortanix-vme/tests/iron",
    "fortanix-vme/tests/nsm-test",
    "intel-sgx/aesm-client",
    "intel-sgx/dcap-provider",
    "intel-sgx/dcap-ql-sys",
    "intel-sgx/dcap-ql",
    "intel-sgx/dcap-retrieve-pckid",
    "intel-sgx/enclave-runner",
    "intel-sgx/fortanix-sgx-abi",
    "intel-sgx/fortanix-sgx-tools",
    "intel-sgx/report-test",
    "intel-sgx/sgxs",
    "intel-sgx/sgx-isa",
    "intel-sgx/sgx_pkix",
    "intel-sgx/sgxs-loaders",
    "intel-sgx/sgxs-tools",
    "ipc-queue",
    "rs-libc",
    "em-app",
    "em-app/examples/get-certificate/",
    "em-app/examples/harmonize/",
]
exclude = ["examples"]

[patch.crates-io]
libc  = { git = "https://github.com/fortanix/libc.git", branch = "fortanixvme" }
mbedtls = { git = "https://github.com/fortanix/rust-mbedtls", branch = "master" }
nix   = { git = "https://github.com/fortanix/nix.git", branch = "raoul/fortanixvme_r0.20.2" }
serde = { git = "https://github.com/fortanix/serde.git", branch = "raoul/stdlib_1.0.136" }
serde_cbor = { git = "https://github.com/fortanix/cbor.git", branch = "raoul/stdlib_serde_1.0.136" }
serde_bytes = { git = "https://github.com/fortanix/bytes.git", branch = "raoul/no_std_compatibility" }
vsock = { git = "https://github.com/fortanix/vsock-rs.git", branch = "fortanixvme" }
rustc-serialize = { git = "https://github.com/jethrogb/rustc-serialize.git", branch = "portability" }
nsm-driver = { git = "https://github.com/fortanix/aws-nitro-enclaves-nsm-api", branch = "raoul/no_std_compatible" }
nsm-io = { git = "https://github.com/fortanix/aws-nitro-enclaves-nsm-api", branch = "raoul/no_std_compatible" }
