[package]
name = "nsm"
version = "0.1.0"
authors = ["Raoul Strackx <raoul.strackx@fortanix.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }
compiler_builtins = { version = "0.1.0", optional = true }
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
nitro-attestation-verify = { path = "../nitro-attestation-verify", optional = true }
nsm-driver = { version = "0.2.0", git = "https://github.com/fortanix/aws-nitro-enclaves-nsm-api", branch = "raoul/no_std_compatible", default-features = false }
nsm-io = { version = "0.2.0", git = "https://github.com/fortanix/aws-nitro-enclaves-nsm-api", branch = "raoul/no_std_compatible", default-features = false }
serde_bytes = { version = "0.11", optional = true }

[features]
default = ["std", "attestation"]
std = ["nsm-driver/std"]
attestation = ["nitro-attestation-verify", "serde_bytes", "nsm-driver/std", "nsm-io/std"]
rustc-dep-of-std = ['alloc', 'core', 'compiler_builtins', "nsm-driver/rustc-dep-of-std", "nsm-io/rustc-dep-of-std"]
