[package]
name = "ias"
version = "0.2.0"
authors = ["Fortanix, Inc."]
license = "MPL-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
bitflags = "1"
byteorder = "1.0"
log = "0.4"
once_cell = "1.13.0"
percent-encoding = "2.1"
serde_bytes = "0.11"
serde-bytes-repr = "0.1"
serde_json = "1"
serde = { version = "1.0.7", features = ["derive"] }
url = "2.2"

mbedtls = { version = "0.8.0", features = ["std"], default-features = false, optional = true }
pkix = "0.1"

sgx-isa = { version = "0.4", path = "../sgx-isa" }
sgx_pkix = { version = "0.1", path = "../sgx_pkix" }

[build-dependencies]
rustc_version = "0.4.0"

[target.'cfg(not(target_env="sgx"))'.dependencies]
reqwest = { version = "0.11", features = ["json"], optional = true }

[features]
client = ["reqwest"]
client-certificate = ["reqwest/native-tls"]
default = ["ias_versions"]
ias_versions = ["ias_version_v4", "ias_version_v3"]
ias_version_v4 = []
ias_version_v3 = []
manipulate_attestation = []

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }

[target.'cfg(not(target_env="sgx"))'.dev-dependencies]
clap = "2.23.3"
env_logger = "0.9.0"

report-test = { version = "0.3", path = "../report-test" }
aesm-client = { version = "0.5", features = ["sgxs"], path = "../aesm-client" }
sgxs = { version = "0.7", path = "../sgxs" }
sgxs-loaders = { version = "0.3", path = "../sgxs-loaders" }

[[example]]
name = "attestation-tool"
required-features = ["client", "mbedtls"]
